### ISSUE TITLE
Melhorar comportamento quando se digita (Número) + (Operador) + (Igual)

### ISSUE THREAD

**Issue by caio-sts** [devJulio96/devJulio96.github.io#2]
A operação
`(Número) + (Operador) + (Igual)`

resulta em "Erro", mas poderia não fazer nada no visor (ou emitir um alert), até que o usuário colocasse o segundo número e apertasse igual

**Comment by devJulio96** [comment]
Correção será realizada realizada.

Ao realizar `(Número)  + (Operador) + (Igual)`  nenhuma será realizada.

Edit: Correção realizada no commit "Correção de Issue"
